import type { Recipe, Profile } from '../types'

// ── Standaardprofiel (lean bulk, 82 kg) ─────────────────────────────
export const defaultProfile: Profile = {
  id: 1,
  weight: 82,
  goalWeight: 88,
  targets: { kcal: 2900, protein: 165, carbs: 380, fat: 80 },
  officeDays: [2, 4], // dinsdag & donderdag (ISO: 1=ma ... 7=zo)
  creatineEnabled: true,
  creatineDoneDates: [],
  darkMode: false,
  supermarket: 'Lidl',
}

// ── Receptenbibliotheek ─────────────────────────────────────────────
// Macro's zijn per portie en zijn RICHTWAARDEN (schattingen).
// Bij avondgerechten is `macros` de Jordi-variant (niet-vis).
export const seedRecipes: Recipe[] = [
  // ── ONTBIJT ──────────────────────────────────────────────────────
  {
    id: 'overnight-oats',
    name: 'Overnight oats basis',
    category: 'ontbijt',
    emoji: '🥣',
    servings: 1,
    prepTimeMin: 5,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 650, protein: 45, carbs: 75, fat: 18 },
    ingredients: [
      { name: 'Havermout', qty: 80, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Halfvolle melk', qty: 200, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Pindakaas', qty: 15, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Chiazaad', qty: 10, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
    ],
    steps: [
      'Meng havermout, melk, whey en chiazaad in een bakje of pot.',
      'Zet een nacht in de koelkast.',
      "'s Ochtends toppen met banaan en pindakaas.",
    ],
  },
  {
    id: 'kwark-oats',
    name: 'Kwark-oats bakje',
    category: 'ontbijt',
    emoji: '🥣',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 3,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk'],
    macros: { kcal: 480, protein: 38, carbs: 55, fat: 12 },
    ingredients: [
      { name: 'Magere kwark', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Havermout', qty: 40, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Bosvruchten (diepvries)', qty: 100, unit: 'g', aisle: 'Diepvries' },
      { name: 'Honing', qty: 20, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Gemengde noten', qty: 15, unit: 'g', aisle: 'Overig' },
    ],
    steps: [
      'Meng kwark met havermout en honing.',
      'Laat 10 min wellen (of een nacht in de koelkast).',
      'Toppen met bosvruchten en noten.',
    ],
  },

  // ── LUNCH — koud & meeneembaar ───────────────────────────────────
  {
    id: 'pasta-kip-salade',
    name: 'Pasta-kip salade',
    category: 'lunch-koud',
    emoji: '🥗',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 620, protein: 48, carbs: 70, fat: 16 },
    ingredients: [
      { name: 'Volkoren pasta (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Cherrytomaat', qty: 1, unit: 'handje', aisle: 'Groente & Fruit' },
      { name: 'Komkommer', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Mais', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Pesto', qty: 20, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Magere yoghurt', qty: 2, unit: 'el', aisle: 'Zuivel & Eieren' },
    ],
    steps: [
      'Kook de pasta en laat afkoelen.',
      'Bak en kruid de kipfilet, laat afkoelen.',
      'Snijd de groente. Meng alles met pesto + yoghurt.',
      'Koud bewaren in een meeneembak.',
    ],
  },
  {
    id: 'couscous-kip-salade',
    name: 'Couscous-kip salade',
    category: 'lunch-koud',
    emoji: '🥗',
    servings: 1,
    prepTimeMin: 15,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 600, protein: 45, carbs: 68, fat: 15 },
    ingredients: [
      { name: 'Couscous', qty: 80, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Paprika', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Feta', qty: 30, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Kikkererwten', qty: 80, unit: 'g', aisle: 'Overig' },
      { name: 'Citroen', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Olijfolie', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Wel de couscous met heet water, roer los met een vork.',
      'Bak en kruid de kip, laat afkoelen.',
      'Meng couscous met kip, paprika, feta, kikkererwten, citroen en olijfolie.',
    ],
  },
  {
    id: 'wraps-kip',
    name: 'Wraps kip',
    category: 'lunch-koud',
    emoji: '🌯',
    servings: 1,
    prepTimeMin: 10,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 560, protein: 42, carbs: 55, fat: 16 },
    ingredients: [
      { name: 'Volkoren wraps', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
      { name: 'Kipfilet', qty: 120, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Hummus', qty: 40, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Sla', qty: 1, unit: 'handje', aisle: 'Groente & Fruit' },
      { name: 'Tomaat', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Magere kaas', qty: 30, unit: 'g', aisle: 'Zuivel & Eieren' },
    ],
    steps: [
      'Besmeer de wraps met hummus.',
      'Beleg met kip, sla, tomaat en kaas.',
      'Rol strak op en verpak in folie.',
    ],
  },
  {
    id: 'snel-kwarkbakje-lunch',
    name: 'Snel kwarkbakje-lunch',
    category: 'lunch-koud',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor', 'snel'],
    macros: { kcal: 520, protein: 45, carbs: 60, fat: 8 },
    ingredients: [
      { name: 'Magere kwark', qty: 400, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Granola', qty: 50, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Fruit', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Doe kwark in een bakje.', 'Top met granola en fruit vlak voor het eten.'],
  },

  // ── AVOND — warm, met vis-swap variant ───────────────────────────
  {
    id: 'nasi',
    name: 'Nasi',
    category: 'avond',
    emoji: '🍛',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 700, protein: 50, carbs: 85, fat: 15 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Ei', qty: 1, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Wokgroente', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Nasikruiden', qty: 1, unit: 'zakje', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de rijst.',
      'Wok de groente met ui, ei en nasikruiden.',
      'Bak het eiwit apart en meng erdoor.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '+150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 700, protein: 50, carbs: 85, fat: 15 },
      },
      {
        person: 'Frederiek',
        label: '+125 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 125, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 760, protein: 42, carbs: 84, fat: 26 },
      },
    ],
  },
  {
    id: 'pasta-bolognese',
    name: 'Pasta bolognese',
    category: 'avond',
    emoji: '🍝',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 720, protein: 48, carbs: 80, fat: 22 },
    ingredients: [
      { name: 'Pasta', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Passata', qty: 200, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Knoflook', qty: 2, unit: 'teen', aisle: 'Groente & Fruit' },
      { name: 'Italiaanse kruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook de pasta.',
      'Fruit ui en knoflook, voeg passata + kruiden toe.',
      'Voeg het eiwit toe en laat sudderen. Serveer over de pasta.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 720, protein: 48, carbs: 80, fat: 22 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis) i.p.v. gehakt',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 620, protein: 45, carbs: 78, fat: 10 },
      },
    ],
  },
  {
    id: 'noodles-roerbak',
    name: 'Noodles roerbak',
    category: 'avond',
    emoji: '🍜',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 680, protein: 45, carbs: 82, fat: 16 },
    ingredients: [
      { name: 'Noodles', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Roerbakgroente', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Sojasaus', qty: 2, unit: 'el', aisle: 'Sauzen & Kruiden' },
      { name: 'Knoflook', qty: 1, unit: 'teen', aisle: 'Groente & Fruit' },
      { name: 'Gember', qty: 1, unit: 'cm', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de noodles.',
      'Wok groente met knoflook en gember.',
      'Voeg eiwit, noodles en sojasaus toe en meng door.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 680, protein: 45, carbs: 82, fat: 16 },
      },
      {
        person: 'Frederiek',
        label: '125 g zalm of garnalen (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 125, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 720, protein: 40, carbs: 80, fat: 22 },
      },
    ],
  },
  {
    id: 'kip-shoarma-rijst',
    name: 'Kip shoarma met rijst',
    category: 'avond',
    emoji: '🍚',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 700, protein: 52, carbs: 80, fat: 16 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Shoarmakruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Paprika', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Lichte knoflooksaus', qty: 30, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook de rijst.',
      'Kruid het eiwit met shoarmakruiden en bak met ui en paprika.',
      'Serveer met rijst en een lepel knoflooksaus.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 700, protein: 52, carbs: 80, fat: 16 },
      },
      {
        person: 'Frederiek',
        label: '150 g witvis/zalm shoarma-stijl (vis)',
        extraIngredients: [{ name: 'Witvis', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 700, protein: 44, carbs: 78, fat: 22 },
      },
    ],
  },
  {
    id: 'rundergehakt-rijst-broccoli',
    name: 'Rundergehakt met rijst & broccoli',
    category: 'avond',
    emoji: '🍚',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 710, protein: 48, carbs: 78, fat: 20 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Broccoli', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Kruiden naar keuze', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook rijst en broccoli.',
      'Bak het eiwit met ui en kruiden.',
      'Serveer samen.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 710, protein: 48, carbs: 78, fat: 20 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 720, protein: 42, carbs: 76, fat: 26 },
      },
    ],
  },
  {
    id: 'kip-curry-rijst',
    name: 'Kip-curry met rijst',
    category: 'avond',
    emoji: '🍛',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 720, protein: 50, carbs: 82, fat: 18 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Currysaus', qty: 150, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Groentemix', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de rijst.',
      'Bak het eiwit, voeg groente en currysaus toe.',
      'Laat kort sudderen en serveer met rijst.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 720, protein: 50, carbs: 82, fat: 18 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 650, protein: 44, carbs: 80, fat: 12 },
      },
    ],
  },

  // ── SHAKES ───────────────────────────────────────────────────────
  {
    id: 'whey-shake',
    name: 'Whey basis shake',
    category: 'shake',
    emoji: '🥤',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 330, protein: 32, carbs: 35, fat: 6 },
    ingredients: [
      { name: 'Whey', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 250, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Blend alles glad.', 'Tip: voeg 3–5 g creatine toe.'],
  },
  {
    id: 'mass-gainer-shake',
    name: 'Mass gainer shake',
    category: 'shake',
    emoji: '🥤',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'kcal-boost'],
    macros: { kcal: 800, protein: 55, carbs: 80, fat: 28 },
    ingredients: [
      { name: 'Whey', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 400, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Havermout', qty: 60, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Pindakaas', qty: 30, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Blend alles glad.', 'Handig als je moeite hebt je kcal te halen.'],
  },

  // ── SNACKS ───────────────────────────────────────────────────────
  {
    id: 'skyr-noten',
    name: 'Skyr + noten',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 1,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 280, protein: 30, carbs: 12, fat: 12 },
    ingredients: [
      { name: 'Skyr', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Amandelen', qty: 20, unit: 'g', aisle: 'Overig' },
    ],
    steps: ['Skyr in een bakje, toppen met amandelen.'],
  },
  {
    id: 'high-protein-pudding',
    name: 'Lidl High Protein pudding',
    category: 'snack',
    emoji: '🍮',
    servings: 1,
    prepTimeMin: 1,
    fridgeDays: 5,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 180, protein: 30, carbs: 8, fat: 3 },
    ingredients: [
      { name: 'High Protein pudding', qty: 1, unit: 'beker', aisle: 'Zuivel & Eieren' },
    ],
    steps: ['Openen en eten.'],
  },
  {
    id: 'kwark-fruit-kaneel',
    name: 'Kwark met fruit & kaneel',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 200, protein: 28, carbs: 15, fat: 3 },
    ingredients: [
      { name: 'Magere kwark', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Fruit', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Kaneel', qty: 1, unit: 'snuf', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Meng kwark met fruit en kaneel.'],
  },
  {
    id: 'eieren-rijstwafels',
    name: 'Gekookte eieren + rijstwafels',
    category: 'snack',
    emoji: '🥚',
    servings: 1,
    prepTimeMin: 10,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk'],
    macros: { kcal: 280, protein: 22, carbs: 20, fat: 15 },
    ingredients: [
      { name: 'Eieren', qty: 3, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Rijstwafels', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
    ],
    steps: ['Kook de eieren (8–9 min).', 'Serveer met rijstwafels.'],
  },
  {
    id: 'kaas-crackers',
    name: 'Magere kaas + volkoren crackers',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 250, protein: 20, carbs: 18, fat: 11 },
    ingredients: [
      { name: 'Magere kaas', qty: 2, unit: 'plak', aisle: 'Zuivel & Eieren' },
      { name: 'Volkoren crackers', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
    ],
    steps: ['Beleg de crackers met kaas.'],
  },
]
