import type { Recipe, Profile } from '../types'

// ── Standaardprofiel (lean bulk, 82 kg) ─────────────────────────────
export const defaultProfile: Profile = {
  id: 1,
  weight: 82,
  goalWeight: 88,
  targets: { kcal: 2900, protein: 165, carbs: 380, fat: 80 },
  officeDays: [2, 4], // dinsdag & donderdag (ISO: 1=ma ... 7=zo)
  cookDays: [7, 4], // zondag + donderdag(avond) prep-sessies
  sharedSlots: ['ontbijt', 'avond'], // samen met Frederiek
  partnerName: 'Frederiek',
  creatineEnabled: true,
  creatineDoneDates: [],
  darkMode: false,
  supermarket: 'Lidl',
}

// Bronnen voor de online recepten (links om verder op te zoeken)
const SRC_FUEL_RECEPTEN = 'https://www.fuelyourbody.nl/blog/meal-prep-recepten'
const SRC_FUEL_ONTBIJT = 'https://www.fuelyourbody.nl/blog/meal-prep-ontbijt.html'
const SRC_MEXICAN = 'https://www.tiktok.com/@jalalsamfit/video/7257206362831146267'
// Gezonde high-protein bak-recepten (voor Fre die graag bakt)
const SRC_LEMON = 'https://tishasveggieeats.com/high-protein-mango-lemon-shortbread-bars/'
const SRC_BANANABREAD = 'https://ohsnapmacros.com/protein-banana-bread/'
const SRC_YOGHURTKOEKJES = 'https://mattsfitchef.com/protein-cookies-with-greek-yogurt/'
const SRC_BAKEDOATS = 'https://eatthegains.com/protein-baked-oatmeal/'

// ── Receptenbibliotheek ─────────────────────────────────────────────
// Macro's zijn per portie en zijn RICHTWAARDEN (schattingen).
// Bij avondgerechten is `macros` de Jordi-variant (niet-vis).
export const seedRecipes: Recipe[] = [
  // ── ONTBIJT ──────────────────────────────────────────────────────
  {
    id: 'overnight-oats',
    name: 'Overnight oats basis',
    category: 'ontbijt',
    emoji: '🥣',
    servings: 1,
    prepTimeMin: 5,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 650, protein: 45, carbs: 75, fat: 18 },
    ingredients: [
      { name: 'Havermout', qty: 80, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Halfvolle melk', qty: 200, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Pindakaas', qty: 15, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Chiazaad', qty: 10, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
    ],
    steps: [
      'Meng havermout, melk, whey en chiazaad in een bakje of pot.',
      'Zet een nacht in de koelkast.',
      "'s Ochtends toppen met banaan en pindakaas.",
    ],
  },
  {
    id: 'kwark-oats',
    name: 'Kwark-oats bakje',
    category: 'ontbijt',
    emoji: '🥣',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 3,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk'],
    macros: { kcal: 480, protein: 38, carbs: 55, fat: 12 },
    ingredients: [
      { name: 'Magere kwark', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Havermout', qty: 40, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Bosvruchten (diepvries)', qty: 100, unit: 'g', aisle: 'Diepvries' },
      { name: 'Honing', qty: 20, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Gemengde noten', qty: 15, unit: 'g', aisle: 'Overig' },
    ],
    steps: [
      'Meng kwark met havermout en honing.',
      'Laat 10 min wellen (of een nacht in de koelkast).',
      'Toppen met bosvruchten en noten.',
    ],
  },

  // ── LUNCH — koud & meeneembaar ───────────────────────────────────
  {
    id: 'pasta-kip-salade',
    name: 'Pasta-kip salade',
    category: 'lunch-koud',
    emoji: '🥗',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 620, protein: 48, carbs: 70, fat: 16 },
    ingredients: [
      { name: 'Volkoren pasta (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Cherrytomaat', qty: 1, unit: 'handje', aisle: 'Groente & Fruit' },
      { name: 'Komkommer', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Mais', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Pesto', qty: 20, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Magere yoghurt', qty: 2, unit: 'el', aisle: 'Zuivel & Eieren' },
    ],
    steps: [
      'Kook de pasta en laat afkoelen.',
      'Bak en kruid de kipfilet, laat afkoelen.',
      'Snijd de groente. Meng alles met pesto + yoghurt.',
      'Koud bewaren in een meeneembak.',
    ],
  },
  {
    id: 'couscous-kip-salade',
    name: 'Couscous-kip salade',
    category: 'lunch-koud',
    emoji: '🥗',
    servings: 1,
    prepTimeMin: 15,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 600, protein: 45, carbs: 68, fat: 15 },
    ingredients: [
      { name: 'Couscous', qty: 80, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Paprika', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Feta', qty: 30, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Cherrytomaat', qty: 100, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Citroen', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Olijfolie', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Wel de couscous met heet water, roer los met een vork.',
      'Bak en kruid de kip, laat afkoelen.',
      'Meng couscous met kip, paprika, feta, cherrytomaat, citroen en olijfolie.',
    ],
  },
  {
    id: 'wraps-kip',
    name: 'Wraps kip',
    category: 'lunch-koud',
    emoji: '🌯',
    servings: 1,
    prepTimeMin: 10,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 560, protein: 42, carbs: 55, fat: 16 },
    ingredients: [
      { name: 'Volkoren wrap', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
      { name: 'Kipfilet', qty: 120, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Hummus', qty: 40, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Sla', qty: 1, unit: 'handje', aisle: 'Groente & Fruit' },
      { name: 'Tomaat', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Magere kaas', qty: 30, unit: 'g', aisle: 'Zuivel & Eieren' },
    ],
    steps: [
      'Besmeer de wraps met hummus.',
      'Beleg met kip, sla, tomaat en kaas.',
      'Rol strak op en verpak in folie.',
    ],
  },
  {
    id: 'snel-kwarkbakje-lunch',
    name: 'Snel kwarkbakje-lunch',
    category: 'lunch-koud',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor', 'snel'],
    macros: { kcal: 520, protein: 45, carbs: 60, fat: 8 },
    ingredients: [
      { name: 'Magere kwark', qty: 400, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Granola', qty: 50, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Fruit', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Doe kwark in een bakje.', 'Top met granola en fruit vlak voor het eten.'],
  },

  // ── AVOND — warm, met vis-swap variant ───────────────────────────
  {
    id: 'nasi',
    name: 'Nasi',
    category: 'avond',
    emoji: '🍛',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 700, protein: 50, carbs: 85, fat: 15 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Ei', qty: 1, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Wokgroente', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Nasikruiden', qty: 1, unit: 'zakje', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de rijst.',
      'Wok de groente met ui, ei en nasikruiden.',
      'Bak het eiwit apart en meng erdoor.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '+150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 700, protein: 50, carbs: 85, fat: 15 },
      },
      {
        person: 'Frederiek',
        label: '+125 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 125, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 760, protein: 42, carbs: 84, fat: 26 },
      },
    ],
  },
  {
    id: 'pasta-bolognese',
    name: 'Pasta bolognese',
    category: 'avond',
    emoji: '🍝',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 720, protein: 48, carbs: 80, fat: 22 },
    ingredients: [
      { name: 'Pasta', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Passata', qty: 200, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Knoflook', qty: 2, unit: 'teen', aisle: 'Groente & Fruit' },
      { name: 'Italiaanse kruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook de pasta.',
      'Fruit ui en knoflook, voeg passata + kruiden toe.',
      'Voeg het eiwit toe en laat sudderen. Serveer over de pasta.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 720, protein: 48, carbs: 80, fat: 22 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis) i.p.v. gehakt',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 620, protein: 45, carbs: 78, fat: 10 },
      },
    ],
  },
  {
    id: 'noodles-roerbak',
    name: 'Noodles roerbak',
    category: 'avond',
    emoji: '🍜',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 680, protein: 45, carbs: 82, fat: 16 },
    ingredients: [
      { name: 'Noodles', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Roerbakgroente', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Sojasaus', qty: 2, unit: 'el', aisle: 'Sauzen & Kruiden' },
      { name: 'Knoflook', qty: 1, unit: 'teen', aisle: 'Groente & Fruit' },
      { name: 'Gember', qty: 1, unit: 'cm', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de noodles.',
      'Wok groente met knoflook en gember.',
      'Voeg eiwit, noodles en sojasaus toe en meng door.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 680, protein: 45, carbs: 82, fat: 16 },
      },
      {
        person: 'Frederiek',
        label: '125 g zalm of garnalen (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 125, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 720, protein: 40, carbs: 80, fat: 22 },
      },
    ],
  },
  {
    id: 'kip-shoarma-rijst',
    name: 'Kip shoarma met rijst',
    category: 'avond',
    emoji: '🍚',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 700, protein: 52, carbs: 80, fat: 16 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Shoarmakruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Paprika', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Lichte knoflooksaus', qty: 30, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook de rijst.',
      'Kruid het eiwit met shoarmakruiden en bak met ui en paprika.',
      'Serveer met rijst en een lepel knoflooksaus.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 700, protein: 52, carbs: 80, fat: 16 },
      },
      {
        person: 'Frederiek',
        label: '150 g witvis/zalm shoarma-stijl (vis)',
        extraIngredients: [{ name: 'Witvis', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 700, protein: 44, carbs: 78, fat: 22 },
      },
    ],
  },
  {
    id: 'rundergehakt-rijst-broccoli',
    name: 'Rundergehakt met rijst & broccoli',
    category: 'avond',
    emoji: '🍚',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 710, protein: 48, carbs: 78, fat: 20 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Broccoli', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Kruiden naar keuze', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kook rijst en broccoli.',
      'Bak het eiwit met ui en kruiden.',
      'Serveer samen.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 710, protein: 48, carbs: 78, fat: 20 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 720, protein: 42, carbs: 76, fat: 26 },
      },
    ],
  },
  {
    id: 'kip-curry-rijst',
    name: 'Kip-curry met rijst',
    category: 'avond',
    emoji: '🍛',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk'],
    macros: { kcal: 720, protein: 50, carbs: 82, fat: 18 },
    ingredients: [
      { name: 'Rijst (droog)', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Currysaus', qty: 150, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Groentemix', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Kook de rijst.',
      'Bak het eiwit, voeg groente en currysaus toe.',
      'Laat kort sudderen en serveer met rijst.',
    ],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 720, protein: 50, carbs: 82, fat: 18 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 650, protein: 44, carbs: 80, fat: 12 },
      },
    ],
  },

  // ── SHAKES ───────────────────────────────────────────────────────
  {
    id: 'whey-shake',
    name: 'Whey basis shake',
    category: 'shake',
    emoji: '🥤',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 330, protein: 32, carbs: 35, fat: 6 },
    ingredients: [
      { name: 'Whey', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 250, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Blend alles glad.', 'Tip: voeg 3–5 g creatine toe.'],
  },
  {
    id: 'mass-gainer-shake',
    name: 'Mass gainer shake',
    category: 'shake',
    emoji: '🥤',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'kcal-boost'],
    macros: { kcal: 800, protein: 55, carbs: 80, fat: 28 },
    ingredients: [
      { name: 'Whey', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 400, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Havermout', qty: 60, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Pindakaas', qty: 30, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Blend alles glad.', 'Handig als je moeite hebt je kcal te halen.'],
  },

  // ── SNACKS ───────────────────────────────────────────────────────
  {
    id: 'skyr-noten',
    name: 'Skyr + noten',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 1,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 280, protein: 30, carbs: 12, fat: 12 },
    ingredients: [
      { name: 'Skyr', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Amandelen', qty: 20, unit: 'g', aisle: 'Overig' },
    ],
    steps: ['Skyr in een bakje, toppen met amandelen.'],
  },
  {
    id: 'high-protein-pudding',
    name: 'Lidl High Protein pudding',
    category: 'snack',
    emoji: '🍮',
    servings: 1,
    prepTimeMin: 1,
    fridgeDays: 5,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 180, protein: 30, carbs: 8, fat: 3 },
    ingredients: [
      { name: 'High Protein pudding', qty: 1, unit: 'beker', aisle: 'Zuivel & Eieren' },
    ],
    steps: ['Openen en eten.'],
  },
  {
    id: 'kwark-fruit-kaneel',
    name: 'Kwark met fruit & kaneel',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 200, protein: 28, carbs: 15, fat: 3 },
    ingredients: [
      { name: 'Magere kwark', qty: 250, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Fruit', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Kaneel', qty: 1, unit: 'snuf', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Meng kwark met fruit en kaneel.'],
  },
  {
    id: 'eieren-rijstwafels',
    name: 'Gekookte eieren + rijstwafels',
    category: 'snack',
    emoji: '🥚',
    servings: 1,
    prepTimeMin: 10,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk'],
    macros: { kcal: 280, protein: 22, carbs: 20, fat: 15 },
    ingredients: [
      { name: 'Eieren', qty: 3, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Rijstwafels', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
    ],
    steps: ['Kook de eieren (8–9 min).', 'Serveer met rijstwafels.'],
  },
  {
    id: 'kaas-crackers',
    name: 'Magere kaas + volkoren crackers',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 250, protein: 20, carbs: 18, fat: 11 },
    ingredients: [
      { name: 'Magere kaas', qty: 2, unit: 'plak', aisle: 'Zuivel & Eieren' },
      { name: 'Volkoren crackers', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
    ],
    steps: ['Beleg de crackers met kaas.'],
  },

  // ══ ONLINE MEAL-PREP RECEPTEN (met bronlink) ═════════════════════
  // ── Extra ontbijt ────────────────────────────────────────────────
  {
    id: 'eiwit-pannenkoeken',
    name: 'Eiwit pannenkoeken',
    category: 'ontbijt',
    emoji: '🥞',
    servings: 1,
    prepTimeMin: 12,
    fridgeDays: 3,
    isColdPortable: true,
    tags: ['eiwitrijk', 'meal-prep', 'koud'],
    macros: { kcal: 520, protein: 56, carbs: 32, fat: 18 },
    sourceUrl: SRC_FUEL_ONTBIJT,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Havermeel', qty: 40, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Eieren', qty: 2, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Griekse yoghurt', qty: 100, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Bosvruchten', qty: 60, unit: 'g', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Mix havermeel, eieren en whey tot een beslag.',
      'Bak kleine pannenkoekjes in een droge koekenpan.',
      'Top met Griekse yoghurt en bosvruchten.',
    ],
  },
  {
    id: 'griekse-yoghurt-bowl',
    name: 'Griekse yoghurt proteïne bowl',
    category: 'ontbijt',
    emoji: '🥣',
    servings: 1,
    prepTimeMin: 4,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['eiwitrijk', 'koud', 'meeneembaar', 'snel'],
    macros: { kcal: 515, protein: 54, carbs: 18, fat: 24 },
    sourceUrl: SRC_FUEL_ONTBIJT,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Griekse yoghurt', qty: 300, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 15, unit: 'g', aisle: 'Overig' },
      { name: 'Gemengde noten', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Chiazaad', qty: 10, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
    ],
    steps: ['Roer whey door de yoghurt.', 'Top met noten en chiazaad.'],
  },
  {
    id: 'baked-oats-blueberry',
    name: 'Baked oats blueberry',
    category: 'ontbijt',
    emoji: '🫐',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['eiwitrijk', 'meal-prep', 'koud'],
    macros: { kcal: 530, protein: 40, carbs: 65, fat: 11 },
    sourceUrl: SRC_FUEL_ONTBIJT,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Havermout', qty: 60, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Ei', qty: 1, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Blauwe bessen', qty: 80, unit: 'g', aisle: 'Groente & Fruit' },
    ],
    steps: [
      'Pureer banaan, mix met havermout, ei en whey.',
      'Roer de bessen erdoor, giet in een ovenschaaltje.',
      'Bak 20 min op 180 °C. Warm of koud te eten.',
    ],
  },
  {
    id: 'breakfast-burrito',
    name: 'Hartige breakfast burrito',
    category: 'ontbijt',
    emoji: '🌯',
    servings: 1,
    prepTimeMin: 12,
    fridgeDays: 2,
    isColdPortable: true,
    tags: ['eiwitrijk', 'koud', 'meeneembaar', 'kantoor'],
    macros: { kcal: 490, protein: 52, carbs: 38, fat: 12 },
    sourceUrl: SRC_FUEL_ONTBIJT,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Volkoren wrap', qty: 1, unit: 'st', aisle: 'Brood & Bakkerij' },
      { name: 'Kipfilet', qty: 100, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Eiwit (los)', qty: 3, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Paprika', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Magere kaas', qty: 20, unit: 'g', aisle: 'Zuivel & Eieren' },
    ],
    steps: [
      'Bak kip en paprika gaar.',
      'Roerbak de eiwitten erbij.',
      'Vul de wrap, rol op en verpak.',
    ],
  },

  // ── Extra avond (met vis-swap) ───────────────────────────────────
  {
    id: 'teriyaki-kip-broccoli',
    name: 'Teriyaki kip met broccoli & rijst',
    category: 'avond',
    emoji: '🍗',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 545, protein: 46, carbs: 62, fat: 7 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Rijst (droog)', qty: 75, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Broccoli', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Teriyakisaus', qty: 40, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Knoflook', qty: 1, unit: 'teen', aisle: 'Groente & Fruit' },
    ],
    steps: ['Kook rijst en broccoli.', 'Bak het eiwit met knoflook.', 'Meng met teriyakisaus.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 545, protein: 46, carbs: 62, fat: 7 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 630, protein: 40, carbs: 60, fat: 24 },
      },
    ],
  },
  {
    id: 'gehakt-zoete-aardappel',
    name: 'Rundergehakt met zoete aardappel & sperziebonen',
    category: 'avond',
    emoji: '🍠',
    servings: 1,
    prepTimeMin: 30,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 520, protein: 41, carbs: 45, fat: 16 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Zoete aardappel', qty: 250, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Sperziebonen', qty: 150, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Kruiden naar keuze', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Rooster de zoete aardappel in de oven.', 'Kook de sperziebonen.', 'Bak het eiwit met ui en kruiden.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 520, protein: 41, carbs: 45, fat: 16 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 600, protein: 40, carbs: 44, fat: 26 },
      },
    ],
  },
  {
    id: 'kip-pesto-pasta',
    name: 'Kip pesto pasta (volkoren)',
    category: 'avond',
    emoji: '🍝',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 575, protein: 42, carbs: 58, fat: 17 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Volkoren penne', qty: 90, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Pesto', qty: 25, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Cherrytomaat', qty: 100, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Courgette', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Kook de pasta.', 'Bak het eiwit met courgette en tomaat.', 'Meng met pesto en pasta.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 575, protein: 42, carbs: 58, fat: 17 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 650, protein: 40, carbs: 56, fat: 28 },
      },
    ],
  },
  {
    id: 'kalkoen-couscous-bowl',
    name: 'Turkse kalkoen bowl met couscous',
    category: 'avond',
    emoji: '🥙',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 515, protein: 42, carbs: 52, fat: 10 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Couscous', qty: 70, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Paprika', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Turkse kruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Wel de couscous.', 'Bak het eiwit met ui, paprika en kruiden.', 'Meng samen tot een bowl.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kalkoengehakt',
        extraIngredients: [{ name: 'Kalkoengehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 515, protein: 42, carbs: 52, fat: 10 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 470, protein: 40, carbs: 50, fat: 8 },
      },
    ],
  },
  {
    id: 'courgetti-bolognese',
    name: 'Courgetti bolognese (low carb)',
    category: 'avond',
    emoji: '🥒',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'low-carb'],
    macros: { kcal: 415, protein: 40, carbs: 20, fat: 17 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Courgette (spiralen)', qty: 300, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Passata', qty: 200, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Italiaanse kruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Maak saus van passata, ui en kruiden met het eiwit.', 'Wok de courgetti kort.', 'Schep de saus erover.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 415, protein: 40, carbs: 20, fat: 17 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 340, protein: 40, carbs: 18, fat: 8 },
      },
    ],
  },
  {
    id: 'bloemkool-kip-curry',
    name: 'Bloemkoolrijst met kip curry (low carb)',
    category: 'avond',
    emoji: '🍛',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'low-carb'],
    macros: { kcal: 390, protein: 42, carbs: 16, fat: 13 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Bloemkoolrijst', qty: 250, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Kokosmelk (light)', qty: 100, unit: 'ml', aisle: 'Overig' },
      { name: 'Currykruiden', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
      { name: 'Ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Bak het eiwit met ui en currykruiden.', 'Voeg kokosmelk toe, laat sudderen.', 'Wok de bloemkoolrijst kort mee.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 390, protein: 42, carbs: 16, fat: 13 },
      },
      {
        person: 'Frederiek',
        label: '150 g witvis (vis)',
        extraIngredients: [{ name: 'Witvis', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 380, protein: 40, carbs: 15, fat: 12 },
      },
    ],
  },
  {
    id: 'gevulde-paprika-gehakt',
    name: "Gevulde paprika's met mager gehakt",
    category: 'avond',
    emoji: '🫑',
    servings: 1,
    prepTimeMin: 35,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 445, protein: 43, carbs: 23, fat: 18 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Paprika', qty: 2, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Hüttenkäse', qty: 100, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Rijst (droog)', qty: 40, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Passata', qty: 100, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Meng het eiwit met gekookte rijst, passata en hüttenkäse.', "Vul de halve paprika's.", 'Bak 25 min op 190 °C.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager gehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 445, protein: 43, carbs: 23, fat: 18 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 380, protein: 40, carbs: 22, fat: 10 },
      },
    ],
  },
  {
    id: 'biefstuk-paksoi',
    name: 'Biefstukreepjes met gewokte paksoi',
    category: 'avond',
    emoji: '🥩',
    servings: 1,
    prepTimeMin: 15,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'low-carb'],
    macros: { kcal: 420, protein: 41, carbs: 13, fat: 20 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Paksoi', qty: 200, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Sojasaus', qty: 2, unit: 'el', aisle: 'Sauzen & Kruiden' },
      { name: 'Knoflook', qty: 1, unit: 'teen', aisle: 'Groente & Fruit' },
      { name: 'Gember', qty: 1, unit: 'cm', aisle: 'Groente & Fruit' },
    ],
    steps: ['Wok knoflook en gember.', 'Bak het eiwit kort aan.', 'Voeg paksoi en sojasaus toe, kort wokken.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g biefstukreepjes',
        extraIngredients: [{ name: 'Biefstukreepjes', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 420, protein: 41, carbs: 13, fat: 20 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 500, protein: 38, carbs: 12, fat: 28 },
      },
    ],
  },
  {
    id: 'burrito-bowl-gehakt',
    name: 'Mexicaanse burrito bowl',
    category: 'avond',
    emoji: '🌮',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 580, protein: 42, carbs: 60, fat: 19 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Rijst (droog)', qty: 75, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Avocado', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Mais', qty: 60, unit: 'g', aisle: 'Overig' },
      { name: 'Mexicaanse kruiden', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
      { name: 'Salsa', qty: 40, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Kook de rijst.', 'Bak het eiwit met kruiden.', 'Bouw de bowl met bonen, mais en salsa.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g mager rundergehakt',
        extraIngredients: [{ name: 'Mager rundergehakt', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 580, protein: 42, carbs: 60, fat: 19 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 510, protein: 42, carbs: 58, fat: 10 },
      },
    ],
  },
  {
    id: 'volkoren-pasta-kip-tomaat',
    name: 'Volkoren pasta met kipreepjes & tomaat',
    category: 'avond',
    emoji: '🍜',
    servings: 1,
    prepTimeMin: 15,
    fridgeDays: 3,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'meal-prep'],
    macros: { kcal: 510, protein: 44, carbs: 58, fat: 11 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Volkoren pasta (droog)', qty: 90, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Passata', qty: 150, unit: 'g', aisle: 'Sauzen & Kruiden' },
      { name: 'Spinazie', qty: 100, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Knoflook', qty: 1, unit: 'teen', aisle: 'Groente & Fruit' },
    ],
    steps: ['Kook de volkoren pasta.', 'Maak saus met passata, knoflook en het eiwit.', 'Roer spinazie erdoor.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g gerookte kipreepjes',
        extraIngredients: [{ name: 'Gerookte kipreepjes', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 510, protein: 44, carbs: 58, fat: 11 },
      },
      {
        person: 'Frederiek',
        label: '150 g garnalen (vis)',
        extraIngredients: [{ name: 'Garnalen', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 470, protein: 42, carbs: 56, fat: 9 },
      },
    ],
  },
  {
    id: 'zalm-quinoa-asperges',
    name: 'Zalm met quinoa en groene asperges',
    category: 'avond',
    emoji: '🐟',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'omega-3'],
    macros: { kcal: 520, protein: 45, carbs: 40, fat: 14 }, // Jordi (kip) variant
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Quinoa', qty: 70, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Groene asperges', qty: 150, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Citroen', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Olijfolie', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Kook de quinoa.', 'Gril de asperges.', 'Bak het eiwit met citroen en olijfolie.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet (niet-vis)',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 520, protein: 45, carbs: 40, fat: 14 },
      },
      {
        person: 'Frederiek',
        label: '150 g zalmfilet (vis)',
        extraIngredients: [{ name: 'Zalmfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 610, protein: 40, carbs: 40, fat: 32 },
      },
    ],
  },
  {
    id: 'kabeljauw-mediterraan',
    name: 'Kabeljauw met mediterrane groenten',
    category: 'avond',
    emoji: '🐟',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 2,
    isColdPortable: false,
    tags: ['warm', 'eiwitrijk', 'low-carb'],
    macros: { kcal: 360, protein: 45, carbs: 15, fat: 9 }, // Jordi (kip) variant
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Courgette', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Cherrytomaat', qty: 150, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Rode ui', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Italiaanse kruiden', qty: 1, unit: 'tl', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Snijd de groenten, meng met kruiden.', 'Leg het eiwit erbovenop.', 'Bak 20 min op 200 °C in de oven.'],
    proteinVariants: [
      {
        person: 'Jordi',
        label: '150 g kipfilet (niet-vis)',
        extraIngredients: [{ name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' }],
        macros: { kcal: 360, protein: 45, carbs: 15, fat: 9 },
      },
      {
        person: 'Frederiek',
        label: '150 g kabeljauwfilet (vis)',
        extraIngredients: [{ name: 'Kabeljauwfilet', qty: 150, unit: 'g', aisle: 'Vis' }],
        macros: { kcal: 335, protein: 41, carbs: 15, fat: 9 },
      },
    ],
  },

  // ── Extra koude lunch ────────────────────────────────────────────
  {
    id: 'quinoa-salade-feta-kip',
    name: 'Quinoa salade met feta & kip',
    category: 'lunch-koud',
    emoji: '🥗',
    servings: 1,
    prepTimeMin: 20,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor'],
    macros: { kcal: 590, protein: 41, carbs: 62, fat: 21 },
    sourceUrl: SRC_FUEL_RECEPTEN,
    sourceName: 'FuelYourBody',
    ingredients: [
      { name: 'Quinoa', qty: 80, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Kipfilet', qty: 150, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Avocado', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Feta', qty: 40, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Komkommer', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Kook de quinoa, laat afkoelen.', 'Bak en kruid de kip.', 'Meng alles koud door elkaar.'],
  },
  {
    id: 'mexican-kip-rijst',
    name: 'Mexicaanse kip & rijst (meal prep)',
    category: 'lunch-koud',
    emoji: '🌶️',
    servings: 1,
    prepTimeMin: 25,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'eiwitrijk', 'kantoor', 'meal-prep'],
    macros: { kcal: 450, protein: 45, carbs: 47, fat: 9 },
    sourceUrl: SRC_MEXICAN,
    sourceName: 'TikTok @jalalsamfit',
    ingredients: [
      { name: 'Kipfilet', qty: 190, unit: 'g', aisle: 'Vlees & Kip' },
      { name: 'Basmatirijst (droog)', qty: 52, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Mais', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Rode paprika', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Ui', qty: 0.5, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Mexicaanse kruiden', qty: 1, unit: 'el', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Kruid de kipblokjes en bak aan.',
      'Voeg ui, paprika en rijst toe, rooster kort mee.',
      'Voeg water/bouillon toe, 12–15 min sudderen. Bonen erdoor, koud bewaren.',
    ],
  },

  // ── Extra shakes & snacks ────────────────────────────────────────
  {
    id: 'choco-pindakaas-shake',
    name: 'Choco-pindakaas shake',
    category: 'shake',
    emoji: '🥤',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'kcal-boost'],
    macros: { kcal: 450, protein: 40, carbs: 40, fat: 16 },
    ingredients: [
      { name: 'Whey (chocolade)', qty: 40, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 300, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Pindakaas', qty: 20, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: ['Blend alles glad.'],
  },
  {
    id: 'groene-eiwit-shake',
    name: 'Groene eiwit-shake',
    category: 'shake',
    emoji: '🥬',
    servings: 1,
    prepTimeMin: 3,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 320, protein: 35, carbs: 28, fat: 8 },
    ingredients: [
      { name: 'Whey (vanille)', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Halfvolle melk', qty: 200, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Spinazie', qty: 30, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Banaan', qty: 1, unit: 'st', aisle: 'Groente & Fruit' },
    ],
    steps: ['Blend alles glad tot een groene shake.'],
  },
  {
    id: 'huttenkase-crackers',
    name: 'Hüttenkäse + volkoren crackers',
    category: 'snack',
    emoji: '🧀',
    servings: 1,
    prepTimeMin: 2,
    fridgeDays: 1,
    isColdPortable: true,
    tags: ['koud', 'eiwitrijk', 'snel'],
    macros: { kcal: 240, protein: 24, carbs: 18, fat: 8 },
    ingredients: [
      { name: 'Hüttenkäse', qty: 150, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Volkoren crackers', qty: 2, unit: 'st', aisle: 'Brood & Bakkerij' },
    ],
    steps: ['Beleg de crackers met hüttenkäse.'],
  },
  {
    id: 'proteine-mueslireep',
    name: 'Proteïne mueslireep',
    category: 'snack',
    emoji: '🍫',
    servings: 1,
    prepTimeMin: 1,
    fridgeDays: 30,
    isColdPortable: true,
    tags: ['koud', 'meeneembaar', 'snel'],
    macros: { kcal: 200, protein: 20, carbs: 20, fat: 6 },
    ingredients: [
      { name: 'Proteïnereep', qty: 1, unit: 'st', aisle: 'Overig' },
    ],
    steps: ['Meenemen en eten wanneer je een snelle eiwitboost nodig hebt.'],
  },

  // ── Gezonde bak-snacks (Fre bakt graag) — macro's per stuk ───────
  {
    id: 'protein-lemon-shortbread',
    name: 'Protein lemon shortbread',
    category: 'snack',
    emoji: '🍋',
    servings: 9, // hele batch = 9 stuks
    prepTimeMin: 40,
    fridgeDays: 5,
    isColdPortable: true,
    tags: ['bakken', 'zoet', 'eiwitrijk', 'koud', 'meeneembaar'],
    macros: { kcal: 136, protein: 14, carbs: 19, fat: 6 }, // per stuk
    sourceUrl: SRC_LEMON,
    sourceName: "Tisha's Veggie Eats",
    ingredients: [
      { name: 'Volkorenmeel', qty: 135, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Roomboter', qty: 42, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Suikervrije siroop', qty: 45, unit: 'ml', aisle: 'Sauzen & Kruiden' },
      { name: 'Citroensap', qty: 110, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Mango', qty: 115, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Eieren', qty: 4, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Zoetstof', qty: 96, unit: 'g', aisle: 'Overig' },
      { name: 'Whey (naturel)', qty: 14, unit: 'g', aisle: 'Overig' },
    ],
    steps: [
      'Bodem: meng meel, boter en siroop, druk in een bakvorm en bak 8–10 min op 175 °C.',
      'Vulling: blend citroensap, mango, eieren, zoetstof, whey en vanille glad.',
      'Giet over de bodem en bak 20–25 min. Laat afkoelen en snijd in 9 stukken.',
    ],
  },
  {
    id: 'protein-bananenbrood',
    name: 'Protein bananenbrood',
    category: 'snack',
    emoji: '🍌',
    servings: 10, // hele cake = ~10 plakken
    prepTimeMin: 55,
    fridgeDays: 4,
    isColdPortable: true,
    tags: ['bakken', 'zoet', 'eiwitrijk', 'meeneembaar'],
    macros: { kcal: 228, protein: 12, carbs: 31, fat: 7 }, // per plak
    sourceUrl: SRC_BANANABREAD,
    sourceName: 'Oh Snap Macros',
    ingredients: [
      { name: 'Volkorenmeel', qty: 180, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Magere Griekse yoghurt', qty: 120, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 60, unit: 'g', aisle: 'Overig' },
      { name: 'Banaan', qty: 3, unit: 'st', aisle: 'Groente & Fruit' },
      { name: 'Eieren', qty: 2, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Bakpoeder', qty: 1, unit: 'tl', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Honing', qty: 30, unit: 'g', aisle: 'Sauzen & Kruiden' },
    ],
    steps: [
      'Pureer de bananen, mix met yoghurt, eieren en honing.',
      'Spatel meel, whey en bakpoeder erdoor.',
      'Bak 45–50 min op 175 °C. Laat afkoelen en snijd in plakken.',
    ],
  },
  {
    id: 'griekse-yoghurt-koekjes',
    name: 'Griekse yoghurt proteïne-koekjes',
    category: 'snack',
    emoji: '🍪',
    servings: 10, // ~10 koekjes
    prepTimeMin: 20,
    fridgeDays: 5,
    isColdPortable: true,
    tags: ['bakken', 'zoet', 'eiwitrijk', 'meeneembaar'],
    macros: { kcal: 90, protein: 7, carbs: 10, fat: 4 }, // per koekje
    sourceUrl: SRC_YOGHURTKOEKJES,
    sourceName: 'Matt’s Fit Chef',
    ingredients: [
      { name: 'Havermout', qty: 100, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Magere Griekse yoghurt', qty: 150, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Whey (vanille)', qty: 30, unit: 'g', aisle: 'Overig' },
      { name: 'Ei', qty: 1, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Pure chocolade', qty: 30, unit: 'g', aisle: 'Overig' },
    ],
    steps: [
      'Meng alles tot een dik beslag, hak de chocolade erdoor.',
      'Schep hoopjes op een bakplaat.',
      'Bak 12–15 min op 180 °C. Laat afkoelen.',
    ],
  },
  {
    id: 'protein-baked-oats-bars',
    name: 'Protein baked oats bars',
    category: 'snack',
    emoji: '🫐',
    servings: 9, // 9 bars
    prepTimeMin: 40,
    fridgeDays: 5,
    isColdPortable: true,
    tags: ['bakken', 'meal-prep', 'eiwitrijk', 'koud', 'meeneembaar'],
    macros: { kcal: 210, protein: 13, carbs: 26, fat: 6 }, // per bar
    sourceUrl: SRC_BAKEDOATS,
    sourceName: 'Eat the Gains',
    ingredients: [
      { name: 'Havermout', qty: 200, unit: 'g', aisle: 'Pasta/Rijst/Droogwaren' },
      { name: 'Whey (vanille)', qty: 60, unit: 'g', aisle: 'Overig' },
      { name: 'Magere Griekse yoghurt', qty: 150, unit: 'g', aisle: 'Zuivel & Eieren' },
      { name: 'Eieren', qty: 2, unit: 'st', aisle: 'Zuivel & Eieren' },
      { name: 'Halfvolle melk', qty: 200, unit: 'ml', aisle: 'Zuivel & Eieren' },
      { name: 'Blauwe bessen', qty: 100, unit: 'g', aisle: 'Groente & Fruit' },
      { name: 'Bakpoeder', qty: 1, unit: 'tl', aisle: 'Pasta/Rijst/Droogwaren' },
    ],
    steps: [
      'Meng alle natte en droge ingrediënten, spatel de bessen erdoor.',
      'Giet in een bakvorm en bak 25–30 min op 180 °C.',
      'Laat afkoelen en snijd in 9 bars.',
    ],
  },
]
